#!/bin/bash -l
#SBATCH --array=0-0
#SBATCH --exclusive
#SBATCH --time=1-00:00
#SBATCH --job-name=Tensor_CSC
#SBATCH --error=logs/job.%J.err
#SBATCH --output=logs/job.%J.out

module load matlab/R2015b
matlab -nodesktop -nosplash -r "grid_search(${SLURM_ARRAY_TASK_ID});quit;"